### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by caichinger** [swkWien/gdcr22#1]
**Was ist passiert?**
- Entwurf für Moderationsslides via Quarto
- Copy-paste von GDCR21 als Referenz
- Bisschen Doku für lokales Setup und Entwicklung

Siehe auch Commit History.

**Was ist zu klären bzw zu tun?**
- [x] Wieso kann ich Rea nicht referenzieren? Nicht admin oder core?
- [x] Verwendung von Header Levels festlegen und Konsistenz prüfen
- [x] Verwendung von Emojis klären --> verwenden wir ;)
- [x] Struktur einer Session als Beispiel/Vorlage anlegen
- [x] Landing Page finalisieren (soweit möglich) (und Slides für Moderation vorerst wieder raus nehmen)
- Bisschen CSS für mehr Farbe? --> verschoben
- [x] Für Links für On Site Moderation QR-Codes erstellen?

*Gehört nicht alles hier her. Nicht alles gleich wichtig.*

**Comment by codecop** [comment]
@ReaSu wurde zum Repo hinzugefügt, jetzt kannst Du sie referenzieren.

**Comment by caichinger** [comment]
> @ReaSu wurde zum Repo hinzugefügt, jetzt kannst Du sie referenzieren.

Habe nicht damit gerechnet, dass diese Nachricht jemand liest - das war mehr ein Gedankenprotokoll. Danke dir.

**Comment by maosmurf** [comment]
@caichinger I suggest stating the times, e.g. "Saturday, 2022-11-05 (9AM-4PM)"  in https://github.com/swkWien/gdcr22/blob/3cebbd118f340199d530d64207dd39dd11a494e5/sessions/_0_landing/_content.qmd#L6

**Comment by caichinger** [comment]
> @caichinger I suggest stating the times, e.g. "Saturday, 2022-11-05 (9AM-4PM)" in
> 
> https://github.com/swkWien/gdcr22/blob/3cebbd118f340199d530d64207dd39dd11a494e5/sessions/_0_landing/_content.qmd#L6

Thank you for your feedback. Yes, I know what you mean. We stated it initially and then decided against it because
* The event start's at 09:00.
* If you join breakfast, it starts earlier.
* You need to register anyway and there you find all details.

Since it occurred to you, let's include it.

You prefer the 12-hour-clock?

This is a version with 24-hour-clock and time

![image](https://user-images.githubusercontent.com/16005912/194263585-83345804-5508-4f90-9dc2-e065d028f203.png)
