### ISSUE TITLE
Slides

### ISSUE THREAD

**Issue by caichinger** [swkWien/gdcr22#2]
@codecop @heidererkatrin @CareForCode @maosmurf @rolger 

Hier ein paar Bitten/Infos:
- Eure Änderungen bitte auf den `dev` Branch (der Inhalt `main` entspricht der Webseite; kein Auskommentieren mehr `ìndex.qmd`).
- Ich/wir werde/n `dev` auf `main` mergen, sobald die Sessions vollständig sind. Ab dann gibt es nur mehr `main`.
- Überlegt euch Fragen für die Retro und nehmt die ggfs. in die Slides mit auf.
- Unser Dokument in https://github.com/swkWien/sessions/blob/master/2022/gdcr/sessions_draft.md ist ein Entwurf, es ist wichtigs dass die groben Ideen erhalten bleiben damit wir den thematischen Bogen spannen können aber die Details der Session nach eigenem Ermessen ausgestalten damit die Session zu euch passt.

Bei Fragen/Problemen mit den Slides bitte rechtzeitig melden.

**Comment by codecop** [comment]
Ich hab meine Session angelegt und Session 2 leicht adaptiert. Ich konnte es nicht testen, weil nichts installiert habe. Bitte schau mal drüber. Von mir aus Session 1 fertig

**Comment by caichinger** [comment]
> Ich hab meine Session angelegt und Session 2 leicht adaptiert. Ich konnte es nicht testen, weil nichts installiert habe. Bitte schau mal drüber. Von mir aus Session 1 fertig

Passt soweit, danke. Kleinigkeiten hab ich gefixed.

**Comment by caichinger** [comment]
Es wird vielleicht Sinn machen, sobald mehr Beiträge da sind, noch einmal drüber zu gehen und die Struktur zu vereinheitlichen.

Sehen wir dann.

**Comment by rolger** [comment]
@caichinger:  Ich habe meine 1. Version hochgeladen. Wenn ich es lokal starte muss ich alle include Pfade anpassen. Es das so richtig oder funktioniert es jetzt am Server nicht mehr?

**Comment by maosmurf** [comment]
@rolger indeed, ich bekomme:
```
ᐅ  quarto render --to revealjs
ERROR: Include directive failed.
  in file /Users/adamzielinski/Documents/pets/gdcr2022/gdcr22/index.qmd,
  in file /Users/adamzielinski/Documents/pets/gdcr2022/gdcr22/sessions/02_pen_and_paper/_content.qmd,
  could not find file sessions/_pairing.qmd.
```

**Comment by caichinger** [comment]
> @caichinger: Ich habe meine 1. Version hochgeladen. Wenn ich es lokal starte muss ich alle include Pfade anpassen. Es das so richtig oder funktioniert es jetzt am Server nicht mehr?

Verstehe das Problem nicht ganz.
Meinem Verständnis nach muss man die Pfade nicht anpassen und der lokale Build entspricht genau dem, was via GitHub Pages per Action veröffentlicht wird.

> @rolger indeed, seit [a6b12db9](https://github.com/swkWien/gdcr22/commit/a6b12db99b1fd67920ef0beb3ef11fa3f9403187) bekomme ich:

Ebenso bei mir. Ich habe die Includes in a44a0e58368c30c7ad8bc93fe8cfdc373686f7bd wieder zurück gesetzt.

**Comment by maosmurf** [comment]
> Ebenso bei mir. Ich habe die Includes in [a44a0e5](https://github.com/swkWien/gdcr22/commit/a44a0e58368c30c7ad8bc93fe8cfdc373686f7bd) wieder zurück gesetzt.

Danke, jetzt passt es auch wieder bei mir.

**Comment by maosmurf** [comment]
I added by slides to a branch, see PR https://github.com/swkWien/gdcr22/pull/3

**Comment by rolger** [comment]
Nachdem ich mir die letzten Änderungen geholt habe, bekomme ich den selben Fehler wieder 

$ ./render.sh
ERROR: Include directive failed.
  in file C:\Users\rolandgerm\projects\community\gdcr22\index.qmd,
  in file sessions/02_pen_and_paper/_content.qmd,
  could not find file C:\Users\rolandgerm\projects\community\_pairing.qmd.

Ist egal, ich werde es einfach nicht lokal testen

**Comment by maosmurf** [comment]
Hm, Wimdows und path separators.
Hast Du WSL (linux subsystem) drauf?

**Comment by caichinger** [comment]
`dev` Branch ist gelöscht, ab jetzt gibt es nur mehr `main`.

Falls ihr was ändert, bitte direkt auf `main`.

Werde noch durch die Folien gehen und gegebenfalls Anpassungen vornehmen.
